service: aws-nodejs # NOTE: update this with your service name

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/book
    - Effect: Allow
      Action: execute-api:invoke
      Resource: arn:aws:execute-api:#{awk::rEGION}:#{AWSq::AccountId}:*/*/GET/books

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
          authorizer: aws_iam

  fetch-books:
    handler: functions/fetch-books.handler
    events:
      - http:
          path: /books/
          method: get
    environment:
      books_table: books

  search-books:
    handler: functions/search-books.handler
    events:
      - http:
          path: /books/search
          method: post
    environment:
      books_table: books

resources:
  Resources:
    libraryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: books
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1