service: aws-nodejs # NOTE: update this with your service name

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/books
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/books #use IAM role to limit the access - 1

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      fetch_books_api: https://8opzfjc5xb.execute-api.us-west-2.amazonaws.com/dev/books
      search_books_api: https://8opzfjc5xb.execute-api.us-west-2.amazonaws.com/dev/books/search
  #A fetch books function
  fetch-books:
    handler: functions/fetch-books.handler
    events:
      - http:
          path: /books/
          method: get
          authorizer: aws_iam #use IAM role to limit the access - 2
    environment:
      books_table: books
  #A search books function
  search-books:
    handler: functions/search-books.handler
    events:
      - http:
          path: /books/search
          method: post
    environment:
      books_table: books
#A DynamoDB table is defined
resources:
  Resources:
    libraryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: books
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

#####
# service: aws-nodejs # NOTE: update this with your service nam

# plugins:
#   - serverless-pseudo-parameters

# provider:
#   name: aws
#   runtime: nodejs12.x
#   region: us-west-2

# functions:
#   get-index:
#     handler: functions/get-index.handler
#     events:
#       - http:
#           path: /
#           method: get